# Generated by Django 2.0.3 on 2018-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compDashboard', '0002_auto_20180626_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('email_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=12, null=True)),
                ('fax_num', models.CharField(blank=True, max_length=12, null=True)),
                ('office_num', models.CharField(blank=True, max_length=7, null=True)),
                ('mail', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
