# Generated by Django 2.0.3 on 2018-07-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compDashboard', '0003_supportstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='event_category',
        ),
        migrations.RemoveField(
            model_name='scrapyitem',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='scrapyitem',
            name='event_time',
        ),
    ]
